apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todolist-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-todolist
  template:
    metadata:
      labels:
        app: django-todolist
    spec:
      containers:
        - name: django-todolist
          image: your-django-image:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-todolist-service
spec:
  selector:
    app: django-todolist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000